/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/audiobookshelf/import-authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk-import all Audiobookshelf authors into the watchlist
         * @description Fetch every author name from ABS libraries and add any unknown ones to the watchlist.
         */
        post: operations["import_authors_api_v1_audiobookshelf_import_authors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audiobookshelf/import-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the last ABS author import result
         * @description Return the result of the most recent ``/import-authors`` call, or
         *     ``{}`` if no import has been run yet (e.g. after a fresh install).
         */
        get: operations["get_import_result_api_v1_audiobookshelf_import_result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audiobookshelf/sync-books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import all Audiobookshelf books and enqueue metadata scans
         * @description Walk every ABS library and import owned books into the DB.
         *
         *     For each item found in ABS:
         *     - Creates the author (+ watchlist entry) if not already known
         *     - Creates the book with ``have_it=True`` if not already present,
         *       using ABS series / position / ISBN / ASIN data directly
         *     - If the book already exists, marks it as owned and fills in any
         *       missing series/identifier fields
         *
         *     After the import a metadata scan is enqueued for every affected author
         *     so that descriptions, cover URLs, and additional series info are filled
         *     in by the normal scan pipeline.
         *
         *     Returns a summary dict with counts and the list of enqueued job IDs.
         */
        post: operations["sync_books_api_v1_audiobookshelf_sync_books_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authors/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List watched authors */
        get: operations["list_authors_api_v1_authors__get"];
        put?: never;
        /** Add author to watchlist */
        post: operations["create_author_api_v1_authors__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authors/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Count authors
         * @description Return ``{"count": N}`` — cheap alternative to fetching the full author list
         *     just to read its length.
         *
         *     ``watched_only=false`` counts all authors in the DB regardless of watchlist membership.
         *     ``active_only`` is only applied when ``watched_only=true``.
         */
        get: operations["count_authors_api_v1_authors_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authors/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List favourite author IDs
         * @description Return ``{"author_ids": [...]}`` — the set of author IDs marked as
         *     favourites.  Stored server-side so the list survives browser clears.
         */
        get: operations["list_favorites_api_v1_authors_favorites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authors/unwatched": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List authors not yet on the watchlist
         * @description Return authors imported from ABS that have no watchlist entry yet.
         *     These are candidates for the user to manually add to the watchlist.
         */
        get: operations["list_unwatched_api_v1_authors_unwatched_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authors/{author_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get author + stats */
        get: operations["get_author_api_v1_authors__author_id__get"];
        put?: never;
        post?: never;
        /** Remove author from watchlist (soft-delete) */
        delete: operations["delete_author_api_v1_authors__author_id__delete"];
        options?: never;
        head?: never;
        /** Update author */
        patch: operations["update_author_api_v1_authors__author_id__patch"];
        trace?: never;
    };
    "/api/v1/authors/{author_id}/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all known name aliases for an author */
        get: operations["list_aliases_api_v1_authors__author_id__aliases_get"];
        put?: never;
        /** Add a name alias for an author */
        post: operations["create_alias_api_v1_authors__author_id__aliases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authors/{author_id}/aliases/{alias_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a name alias */
        delete: operations["delete_alias_api_v1_authors__author_id__aliases__alias_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authors/{author_id}/coauthors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List co-authors for an author
         * @description Return authors who share at least one book with *author_id* as a
         *     co-author, ordered by shared-book count descending.
         */
        get: operations["list_coauthors_api_v1_authors__author_id__coauthors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authors/{author_id}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark author as favourite */
        post: operations["add_favorite_api_v1_authors__author_id__favorite_post"];
        /** Unmark author as favourite */
        delete: operations["remove_favorite_api_v1_authors__author_id__favorite_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authors/{author_id}/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Language breakdown for an author's catalog
         * @description Return a per-language count of books in this author's catalog, ordered
         *     by count descending.  Useful for choosing an appropriate ``language_filter``
         *     before triggering a scan.  The ``language`` field is ``null`` for book rows
         *     that pre-date the v0.48.0 ``books.language`` column.
         */
        get: operations["list_author_languages_api_v1_authors__author_id__languages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authors/{author_id}/watch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add author to watchlist
         * @description Create a watchlist entry for an author imported without one.
         */
        post: operations["watch_author_api_v1_authors__author_id__watch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authors/{author_id}/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Toggle scan_enabled on watchlist entry */
        patch: operations["update_watchlist_api_v1_authors__author_id__watchlist_patch"];
        trace?: never;
    };
    "/api/v1/books/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List books */
        get: operations["list_books_api_v1_books__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Count books matching filter criteria
         * @description Return ``{"count": N}`` — identical filter semantics to ``GET /books/``
         *     but cheap enough to use for dashboard stat cards.
         */
        get: operations["count_books_api_v1_books_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/recently-imported": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Books most recently imported
         * @description Return the most recently imported books (match_method='imported'), newest first.
         *
         *     Ordered by created_at (immutable insert time) rather than updated_at, which
         *     changes on any subsequent metadata update and would produce incorrect ordering.
         */
        get: operations["recently_imported_api_v1_books_recently_imported_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single book */
        get: operations["get_book_api_v1_books__book_id__get"];
        put?: never;
        post?: never;
        /** Soft-delete a book */
        delete: operations["delete_book_api_v1_books__book_id__delete"];
        options?: never;
        head?: never;
        /** Update book fields */
        patch: operations["update_book_api_v1_books__book_id__patch"];
        trace?: never;
    };
    "/api/v1/books/{book_id}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a downloaded file into the library
         * @description Enqueues an ``import_download_task`` that extracts archives and moves
         *     audio files into ``<library_root>/<Author>/<Series>/<Title>/``.
         *
         *     Requires ``postprocess.mode: bookscout`` and a non-empty
         *     ``postprocess.library_root`` in config.yaml.
         */
        post: operations["import_book_api_v1_books__book_id__import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{book_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search indexers for a specific book
         * @description Auto-constructs an indexer search query from the book's title and primary
         *     author name, then queries all configured Prowlarr / Jackett indexers.
         *     Returns the same result shape as ``POST /api/v1/search/``.
         */
        post: operations["search_for_book_api_v1_books__book_id__search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SSE real-time event stream */
        get: operations["event_stream_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library-paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all configured library paths */
        get: operations["list_library_paths_api_v1_library_paths_get"];
        put?: never;
        /** Register a new library path */
        post: operations["add_library_path_api_v1_library_paths_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library-paths/scan-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue a filesystem scan for all enabled library paths */
        post: operations["enqueue_all_library_scans_api_v1_library_paths_scan_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library-paths/{path_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a library path */
        delete: operations["remove_library_path_api_v1_library_paths__path_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library-paths/{path_id}/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue a filesystem scan for a library path */
        post: operations["enqueue_library_scan_api_v1_library_paths__path_id__scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/n8n/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Executions
         * @description Proxy the last N executions for a given n8n workflow.
         *     Returns a simplified list with status, timestamps, and any book-level results.
         */
        get: operations["get_executions_api_v1_n8n_executions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan all active watchlist entries */
        post: operations["scan_all_api_v1_scans_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/author/{author_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan a single author */
        post: operations["scan_author_api_v1_scans_author__author_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/job/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check job status */
        get: operations["job_status_api_v1_scans_job__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scan statistics for the dashboard
         * @description Returns a snapshot of scan activity useful for dashboard stat cards:
         *
         *     - **last_scan_time**: when any author was most recently scanned
         *     - **new_books_today**: books discovered since UTC midnight today
         *     - **total_books**: all non-deleted books
         *     - **total_missing**: non-deleted books not yet owned
         *     - **authors_scanned_today**: watchlist entries scanned since UTC midnight
         */
        get: operations["scan_stats_api_v1_scans_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unified Prowlarr + Jackett search */
        post: operations["search_api_v1_search__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a result to the configured download client */
        post: operations["download_api_v1_search_download_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/download/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch the current download client queue
         * @description Returns every item currently in the configured download client queue(s),
         *     including progress, status, ETA, and destination path.
         *
         *     - **SABnzbd**: active NZB slots with MB remaining + percentage
         *     - **qBittorrent**: all torrents with state, progress (0–100 %), ETA, save path
         *     - **Transmission**: all torrents with state, progress, ETA, download dir
         *     - **Hybrid**: when both SABnzbd and a torrent client are configured, items
         *       from both queues are returned in a single combined list
         */
        get: operations["download_queue_api_v1_search_download_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check indexer and download client connectivity
         * @description Pings every configured indexer and download client and returns their
         *     reachability status — analogous to ``GET /api/v1/abs/status``.
         */
        get: operations["download_status_api_v1_search_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Webhooks */
        get: operations["list_webhooks_api_v1_webhooks__get"];
        put?: never;
        /** Create Webhook */
        post: operations["create_webhook_api_v1_webhooks__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/{webhook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Webhook */
        get: operations["get_webhook_api_v1_webhooks__webhook_id__get"];
        put?: never;
        post?: never;
        /** Delete Webhook */
        delete: operations["delete_webhook_api_v1_webhooks__webhook_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/{webhook_id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deliveries */
        get: operations["list_deliveries_api_v1_webhooks__webhook_id__deliveries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/{webhook_id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-enable an auto-disabled webhook
         * @description Reset ``failure_count`` and re-enable a webhook that was auto-disabled
         *     by dead endpoint detection.  Also works for webhooks deactivated manually
         *     via DELETE if you want to restore them without recreating.
         */
        post: operations["reactivate_webhook_api_v1_webhooks__webhook_id__reactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/{webhook_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a test event to this webhook */
        post: operations["test_webhook_api_v1_webhooks__webhook_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + readiness check */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AliasCreate */
        AliasCreate: {
            /** Alias */
            alias: string;
            /**
             * Source
             * @default manual
             */
            source: string;
        };
        /** AliasOut */
        AliasOut: {
            /** Alias */
            alias: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Source */
            source: string;
        };
        /** AuthorCreate */
        AuthorCreate: {
            /** Name */
            name: string;
        };
        /** AuthorDetailOut */
        AuthorDetailOut: {
            /** Active */
            active: boolean;
            /** Asin */
            asin?: string | null;
            /**
             * Book Count
             * @default 0
             */
            book_count: number;
            /** Created At */
            created_at?: string | null;
            /** Id */
            id: number;
            /** Last Scanned */
            last_scanned?: string | null;
            /** Name */
            name: string;
            /** Name Sort */
            name_sort: string;
            /** Openlibrary Key */
            openlibrary_key?: string | null;
            /**
             * Owned Count
             * @default 0
             */
            owned_count: number;
        };
        /** AuthorOut */
        AuthorOut: {
            /** Active */
            active: boolean;
            /** Asin */
            asin?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Id */
            id: number;
            /** Last Scanned */
            last_scanned?: string | null;
            /** Name */
            name: string;
            /** Name Sort */
            name_sort: string;
            /** Openlibrary Key */
            openlibrary_key?: string | null;
        };
        /** AuthorUpdate */
        AuthorUpdate: {
            /** Active */
            active?: boolean | null;
            /** Name */
            name?: string | null;
        };
        /** BookOut */
        BookOut: {
            /** Asin */
            asin?: string | null;
            /** Confidence Band */
            confidence_band: string;
            /** Cover Url */
            cover_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted */
            deleted: boolean;
            /** Description */
            description?: string | null;
            /** Format */
            format?: string | null;
            /** Have It */
            have_it: boolean;
            /** Id */
            id: number;
            /** Isbn */
            isbn?: string | null;
            /** Isbn13 */
            isbn13?: string | null;
            /** Language */
            language?: string | null;
            /** Match Method */
            match_method: string;
            /** Narrator */
            narrator?: string | null;
            /** Published Year */
            published_year?: number | null;
            /** Release Date */
            release_date?: string | null;
            /** Score */
            score: number;
            /** Score Reasons */
            score_reasons?: string | null;
            /** Series Name */
            series_name?: string | null;
            /** Series Position */
            series_position?: string | null;
            /** Source */
            source?: string | null;
            /** Subtitle */
            subtitle?: string | null;
            /** Title */
            title: string;
            /** Title Sort */
            title_sort: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** BookUpdate */
        BookUpdate: {
            /** Asin */
            asin?: string | null;
            /** Deleted */
            deleted?: boolean | null;
            /** Have It */
            have_it?: boolean | null;
            /** Isbn */
            isbn?: string | null;
            /** Isbn13 */
            isbn13?: string | null;
            /** Language */
            language?: string | null;
            /** Series Name */
            series_name?: string | null;
            /** Series Position */
            series_position?: string | null;
            /** Subtitle */
            subtitle?: string | null;
        };
        /** CoAuthorOut */
        CoAuthorOut: {
            /** Book Count */
            book_count: number;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** On Watchlist */
            on_watchlist: boolean;
        };
        /** DeliveryOut */
        DeliveryOut: {
            /**
             * Delivered At
             * Format: date-time
             */
            delivered_at: string;
            /** Event Type */
            event_type: string;
            /** Id */
            id: number;
            /** Status Code */
            status_code?: number | null;
            /** Success */
            success?: boolean | null;
        };
        /** DownloadRequest */
        DownloadRequest: {
            /**
             * Book Id
             * @default 0
             */
            book_id: number;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Save Path
             * @default
             */
            save_path: string;
            /**
             * Tag
             * @default
             */
            tag: string;
            /** Title */
            title: string;
            /**
             * Type
             * @default torrent
             */
            type: string;
            /** Url */
            url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportRequest */
        ImportRequest: {
            /** Source Path */
            source_path: string;
        };
        /** LanguageCount */
        LanguageCount: {
            /** Count */
            count: number;
            /** Language */
            language: string | null;
        };
        /** LibraryPathCreate */
        LibraryPathCreate: {
            /** Name */
            name?: string | null;
            /** Path */
            path: string;
        };
        /** SearchRequest */
        SearchRequest: {
            /**
             * Query
             * @description Search query forwarded to Prowlarr/Jackett (max 500 chars, alphanumeric + common punctuation).
             */
            query: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchlistSettings */
        WatchlistSettings: {
            /** Scan Enabled */
            scan_enabled?: boolean | null;
        };
        /** WebhookCreate */
        WebhookCreate: {
            /** Description */
            description?: string | null;
            /**
             * Events
             * @default []
             */
            events: string[];
            /** Url */
            url: string;
        };
        /** WebhookOut */
        WebhookOut: {
            /** Active */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description?: string | null;
            /** Disabled At */
            disabled_at?: string | null;
            /** Events */
            events?: string[] | null;
            /**
             * Failure Count
             * @default 0
             */
            failure_count: number;
            /** Id */
            id: number;
            /** Url */
            url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    import_authors_api_v1_audiobookshelf_import_authors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_import_result_api_v1_audiobookshelf_import_result_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    sync_books_api_v1_audiobookshelf_sync_books_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_authors_api_v1_authors__get: {
        parameters: {
            query?: {
                active_only?: boolean;
                /** @description Filter by name (case-insensitive contains) */
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorDetailOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_author_api_v1_authors__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    count_authors_api_v1_authors_count_get: {
        parameters: {
            query?: {
                active_only?: boolean;
                watched_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_favorites_api_v1_authors_favorites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_unwatched_api_v1_authors_unwatched_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorOut"][];
                };
            };
        };
    };
    get_author_api_v1_authors__author_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_author_api_v1_authors__author_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_author_api_v1_authors__author_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthorUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_aliases_api_v1_authors__author_id__aliases_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AliasOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_alias_api_v1_authors__author_id__aliases_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AliasCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AliasOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_alias_api_v1_authors__author_id__aliases__alias_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: number;
                alias_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_coauthors_api_v1_authors__author_id__coauthors_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoAuthorOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_favorite_api_v1_authors__author_id__favorite_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_favorite_api_v1_authors__author_id__favorite_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_author_languages_api_v1_authors__author_id__languages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageCount"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watch_author_api_v1_authors__author_id__watch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_watchlist_api_v1_authors__author_id__watchlist_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistSettings"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_books_api_v1_books__get: {
        parameters: {
            query?: {
                /** @description Filter by primary author */
                author_id?: number | null;
                /** @description high | medium | low */
                confidence_band?: string | null;
                /** @description Owned flag filter */
                have_it?: boolean | null;
                /** @description Shorthand for have_it=false */
                missing_only?: boolean;
                include_deleted?: boolean;
                /** @description ISO 8601 timestamp; return only books whose updated_at is after this value.  Useful for polling workflows (e.g. n8n) that need only the delta since their last run. */
                updated_since?: string | null;
                /** @description Max results to return (1–500) */
                limit?: number;
                /** @description Number of results to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    count_books_api_v1_books_count_get: {
        parameters: {
            query?: {
                /** @description Filter by primary author */
                author_id?: number | null;
                /** @description high | medium | low */
                confidence_band?: string | null;
                /** @description Owned flag filter */
                have_it?: boolean | null;
                /** @description Shorthand for have_it=false */
                missing_only?: boolean;
                include_deleted?: boolean;
                /** @description ISO 8601 timestamp; count only books updated after this value. */
                updated_since?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recently_imported_api_v1_books_recently_imported_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_api_v1_books__book_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_book_api_v1_books__book_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_book_api_v1_books__book_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_book_api_v1_books__book_id__import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_for_book_api_v1_books__book_id__search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    event_stream_api_v1_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_library_paths_api_v1_library_paths_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    add_library_path_api_v1_library_paths_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryPathCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_all_library_scans_api_v1_library_paths_scan_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    remove_library_path_api_v1_library_paths__path_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_library_scan_api_v1_library_paths__path_id__scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_executions_api_v1_n8n_executions_get: {
        parameters: {
            query: {
                /** @description n8n workflow ID */
                workflow_id: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_all_api_v1_scans_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    scan_author_api_v1_scans_author__author_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_status_api_v1_scans_job__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_stats_api_v1_scans_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    search_api_v1_search__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_api_v1_search_download_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DownloadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_queue_api_v1_search_download_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    download_status_api_v1_search_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_webhooks_api_v1_webhooks__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookOut"][];
                };
            };
        };
    };
    create_webhook_api_v1_webhooks__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_webhook_api_v1_webhooks__webhook_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_webhook_api_v1_webhooks__webhook_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deliveries_api_v1_webhooks__webhook_id__deliveries_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reactivate_webhook_api_v1_webhooks__webhook_id__reactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_webhook_api_v1_webhooks__webhook_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
