services:
  bookscout-ui:
    image: ghcr.io/slackerchris/bookscout-ui:1.2.4
    container_name: bookscout-ui
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - bookscout

networks:
  bookscout:
    external: true
